openapi: 3.0.2
info:
  version: '1.0'
  title: Server Variables
  description: For testing Server variables
paths:
  /simple:
    get:
      summary: When no server is specified in the spec.
      description: If there is no server specified in the spec then it should default to `location.origin`. Alternativly an API-Server can be specified in `<rapi-doc>` element using `server-url` attribute
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    description: Person Name
                    type: string
                  age:
                    description: Person Age
                    type: integer