openapi: 3.0.1
info:
  title: Identity Server
  description: OAuth Demo using <a href="https://demo.duendesoftware.com/" target="_blank">IdentityServer</a>
  version: "1.0"
servers:
- url:  https://demo.duendesoftware.com

components:
  securitySchemes:
    short-lived-oauth:
      type: oauth2
      description: Provides an OAuth token thats valid for short duration ~75 seconds
      
      # pre filling client-id, secret and scopes for all flows using vendor extension
      x-client-id: interactive.confidential.short
      x-client-secret: secret
      x-default-scopes:
        openid
      
      flows:
        authorizationCode:
          authorizationUrl: https://demo.duendesoftware.com/connect/authorize
          tokenUrl: https://demo.duendesoftware.com/connect/token
          scopes:
            openid: OpenID
            email: Email 
            profile: Profile 
    long-lived-oauth:
      type: oauth2
      description: Provides an OAuth token thats valid for long durations
      flows:
        authorizationCode:
          authorizationUrl: https://demo.duendesoftware.com/connect/authorize
          tokenUrl: https://demo.duendesoftware.com/connect/token

          # pre filling client-id, secret and scopes for a specific flow using vendor extension
          x-client-id: interactive.confidential
          x-client-secret: secret
          x-default-scopes:
            openid
          # when x-pkce-only=true, it will not allow to provide or send client_secret through the UI
          x-pkce-only: true
          
          scopes:
            openid: OpenID
            email: Email 
            profile: Profile 
paths:
  /api/test:
    get:
      summary: Test API
      description: |
        This API needs an oAuth token with `api` scope. This information can also be found when you hover over Authentication info 
        provided besides the lock icon in the top-right section of this operation. 
        <br/>
        Every operation which has security requiremnts will contain this icon and the details can be checked by hovering above it
      security:
        - short-lived-oauth:
        - long-lived-oauth:
      responses:
        '200':
          description: Successful operation

  /connect/userinfo:
    get:
      summary: Get User Info
      description: |
        This API needs an oAuth token with following one or more scopes
          - `openid`
          - `email`
          - `profile`
        
        based on the scopes in the oAuth token, it will change the response shape. 
        Give it a try by aquiring token with various scope combinations and check out the responses  
      security:
        - short-lived-oauth:
          - openid
          - email
          - profile
        - long-lived-oauth:
          - openid
          - email
          - profile
      responses:
        '200':
          description: Successful operation


