openapi: 3.0.0
info:
  title: ONE-OF with combinations of various data types
  version: '1.0'
paths:
  /one-of-array-and-object:
    get:
      summary: Array and Object containing ONE-OF
      tags:
        - ONE-OF Combinations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  single:
                    oneOf:
                      - type: string
                      - type: object
                        properties:
                          x:
                            type: string
                          y:
                            type: string
                  multiple:
                    type: array
                    items:
                      oneOf:
                        - type: string
                        - type: object
                          properties:
                            x:
                              type: string
                            y:
                              type: string
  /one-of-primitives-and-object:
    get:
      summary: ONE-OF containing Object, premitives & arrays
      description: This **ONE OF** contains `primitives, arrays, objects, arrays of primitives and array of objects`, 
      tags:
        - ONE-OF Combinations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  a:
                    type: string
                  b:
                    type: string
                  c:
                    oneOf:
                      - type: boolean
                      - type: number
                      - type: string
                      - type: object
                        properties:
                          x:
                            type: string
                          y:
                            type: string
                      - type: array
                        title: Cordinates
                        description: Array of Object
                        items:
                          type: object
                          properties:
                            x:
                              type: string
                            y:
                              type: string
                      - type: array
                        title: Array title
                        description: Array of string with title and description
                        items:
                          type: string
                          title: Array Item Title
                      - type: array
                        description: Array of string without a title but has a description
                        items:
                          type: string
                          title: Array Item Title
                      - type: string
                        description: Primitive with a title
                        title: ID number
                      - type: integer
                        description: Primitive without a title
                      - type: 'null'
                        description: Null with a title
                        title: Null with a title
                      - type: 'null'
                        description: Null without a title
                  d:
                    type: string
  /one-of-options-with-array-as-root:
    post:
      summary: ONE-OF Options with Array as root
      tags:
        - ONE-OF Root as Array / Object
      requestBody:
        description: ONE OF Option where root element is an array
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - title: Option 1
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      age:
                        type: integer
                - title: Option 2
                  type: array
                  items:
                    type: object
                    properties:
                      location:
                        type: string
                      pin:
                        type: integer

  /one-of-options-with-object-as-root:
    post:
      summary: ONE-OF Options with Object as root
      tags:
         - ONE-OF Root as Array / Object
      requestBody:
        description: ONE OF Option where root element is an object
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - title: Option 1
                  type: object
                  properties:
                    name:
                      type: string
                    age:
                      type: integer
                - title: Option 2
                  type: object
                  properties:
                    location:
                      type: string
                    zip:
                      type: integer
  /one-of-options-with-object-sibling:
    post:
      summary: ONE-OF Options with Object as sibling
      tags:
         - ONE-OF and Object Sibling
      requestBody:
        description: ONE OF and Object as sibling
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                person:
                  type: object
                  properties:
                    age:
                      type: number
                    name:
                      type: object
                      properties:
                        first:
                          type: string
                        last:
                          type: string
              oneOf:
                - title: Option 1
                  type: object
                  properties:
                    oneof_opt1_prop1:
                      type: string
                    oneof_opt1_prop2:
                      type: integer
                - title: Option 2
                  type: object
                  properties:
                    oneof_opt2_prop1:
                      type: string
                    oneof_opt2_prop2:
                      type: integer

  /one-of-options-with-read-only-items:
    post:
      summary: ONE-OF Options with ReadOnly Items
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                reference:
                  oneOf:
                    - type: object
                      title: ReadOnly Option
                      description: Should be ignored as options cant be ReadOnly
                      properties:
                        foo:
                          type: string
                      readOnly: true
                    - type: object
                      title: Contains ReadOnly Props
                      description: Should be shown as empty object in request bodies
                      properties:
                        bar:
                          type: string
                          readOnly: true
      responses:
        '201':
          description: Created
    